name: cppcheck

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout cppcheck
      uses: actions/checkout@v2
      with:
        repository: danmar/cppcheck
        ref: '2.3'
        path: './cppcheck'
    - name: Test path
      run: pwd
       
#     - name: Build cppcheck
#       run: |
#         cd /home/runner/work/testrepo/testrepo/cppcheck
#         mkdir build && cd build
#         cmake ..
#         make
#         cp -r ../cfg ./bin
#         ls ./bin
#         ls ./bin/cfg
