name: cppcheck

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upgrade then install
      run: sudo apt-get update && apt-get upgrade -y && install cppcheck
    - name: Get version
      run: sudo apt-get cppcheck --version
