name: cppcheck

on: push

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '#skipcppcheck')"
    runs-on: ubuntu-latest
    container:
      image: cppcheck-docker:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cppcheck
      run: |
        cppcheck --version
        cppcheck test.cpp --enable=all --max-ctu-depth=4 --output-file=cppcheck_report.txt --language=c++ --std=c++17 --suppress=missingIncludeSystem
        cat cppcheck_report.txt
