name: cppcheck

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout cppcheck
      uses: actions/checkout@v2
      with:
        repository: danmar/cppcheck
        ref: '2.3'
        path: './cppcheck'
    - name: Build cppcheck
      run: |
        cd cppcheck
        mkdir build && cd build
        cmake ..
        make
        cp -r ../cfg ./bin
    - name: Run cppcheck
      run: |
        cd cppcheck/build/bin
        ./cppcheck ../../../test.cpp --enable=all --max-ctu-depth=4 --output-file=../../../report_cppcheck.txt --language=c++ --std=c++17
        cat ../../../report_cppcheck.txt
